### PR TITLE
Lower threshold to 77.5%, increase window to 1 week

### PR DESCRIPTION
**Pull request by Pttn**
To be honest the activation is more a formality than anything else. Let's lower the threshold, activate and move on.
With a dummy bit as suggested by cryptapus to warn people that still have the 95% threshold.

### CODE REVIEW

**Comment by Pttn** [comment]
Weird, version 536870919 don't seem to be accepted by other nodes :|... I was pretty sure that it would.
Maybe for some reason the dummy bit 2 is rejected...

**Comment by Pttn** [comment]
Just got another problem, now the wallet is stuck at

```
"period": 1152,
"threshold": 864,
"elapsed": 864,
"count": 630,
```

For some reason it bans all other nodes...

**Comment by Pttn** [comment]
Bit 5 seems to be accepted (Block 1080469). Maybe it had something to do with the
```
{
  "id": "bip34",
  "version": 2,
  "reject": {
    "status": true
  }
}
```
I have chosen bit 5 because 3 and 4 might also be used by
```
"id": "bip66",
"version": 3,
"id": "bip65",
"version": 4,
```

**Comment by cryptapus** [comment]
That was going to be my question on your node, with the lower threshold had it already locked in...

I'm wondering if we need an even longer block window. For a mono-algo pow chain I fear anything too short is at risk of unintended consensus... Maybe ~2weeks?

**Comment by Pttn** [comment]
Ok, to be in the safe side, let's require 80% during 2 weeks. It should be an achievable goal, while not being too easy. More than 80% would probably be too hard in our situation.
Please review and confirm that the code doesn't produce unwanted behavior. I will ask others if the new parameters are Ok for them, if there are no disagreements and you confirm that everything is fine, I merge this.

**Comment by cryptapus** [comment]
partially tested ACK.

If you wanted to be very careful, you could alter all `DEPLOYMENT_SEGWIT` and `DEPLOYMENT_CSV` logic to `DEPLOYMENT_SEGWIT && LOWER_THRESHOLD` and `DEPLOYMENT_CSV && LOWER_THRESHOLD` so that `LOWER_THRESHOLD` must also reach 75% before the rules can lock-in. Right now, `LOWER_THRESHOLD` nodes are counting all `DEPLOYMENT_SEGWIT` and `DEPLOYMENT_CSV` blocks (and hence will activate regardless) and that may not be what we want, we want to look for blocks that agree to the newer threshold too. Basically, these BIP9 rules are independent and we want them to all activate at the same time.

Maybe @clo-prime has some thoughts on this as well.

Also, you will want to alter:

https://github.com/riecointeam/riecoin/blob/master/configure.ac#L6

to

    define(_CLIENT_VERSION_BUILD, 1)

to set the version to `v0.16.3.1`.

**Comment by Pttn** [comment]
I get what you mean, however I think that it would be better to let things as they are right now. We wouldn't want to be retained by people that forgot to upgrade (or don't do it on purpose) as it could make the activation much harder and force us to discuss again about another lowering or not requiring anymore the LOWER_THRESHOLD to 80%. It should be them that have to upgrade, not us that have to wait for them.

For the version, done. Once we get at least one more DNS seed we can set the _CLIENT_VERSION_IS_RELEASE back to true and make the release.

Let's see if clo1 has something to say. Otherwise I will merge in 24 h.

**Comment by Pttn** [comment]
After some discussion, it seems that 80%/2 week is still a pretty high requirement. There were some recent 0.16.3 surges that were only temporary, so 80% may be significantly harder than it looks like. However, we cannot set lower than 75% as it was already reached previously.

I am therefore lowering the requirements to 77.5%/1 week. The window should still be wide enough to avoid side effects, and there should be no consequences compared to 80%/2 weeks, so I am merging.

Thank you for the review by the way.

**Comment by clo-prime** [comment]
Sorry, I'm a bit late to this.

Cryptapus' suggestion to use
`DEPLOYMENT_SEGWIT && LOWER_THRESHOLD and DEPLOYMENT_CSV && LOWER_THRESHOLD`
is good but maybe too conservative. At a minimum you need over 50% to use the lower threshold. Otherwise after the threshold is reached the chain will fork and those using the lower threshold will end up on the smaller chain. If more than 50% but not all use the lower threshold you will get some orphans in the first 288 window after activation but then everyone should be activated.

Also, you could have changed the start time if 75% had already been reached.

**Comment by Pttn** [comment]
Ok, as the process already started, I wondered if any side effect could have happened by changing the start time. I think that the current parameters are fine and should allow a possible and safe activation in a not too long timespan.

**Pull request merged**
